In [5]:
import os

print(os.getcwd())

/home/user/Documents/Job-Market-Intelligence-Platform/notebooks

In [6]:
import os

print(os.listdir("../data"))

['clean_jobs.csv']

In [7]:
import pandas as pd

df = pd.read_csv("../data/clean_jobs.csv")
df.head()

,id,title,company,location,link,source,date_posted,work_type,employment_type,description
0,1,Data Analyst,Meta,"New York, NY",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
1,2,Data Analyst,Meta,"San Francisco, CA",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
2,3,Data Analyst,Meta,"Los Angeles, CA",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
3,4,Data Analyst,Meta,"Washington, DC",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
4,5,Data Analyst II,Pinterest,"Chicago, IL",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-16,NaN,NaN,About Pinterest\n\nMillions of people around t...

In [9]:
df.columns

Index(['id', 'title', 'company', 'location', 'link', 'source', 'date_posted',
       'work_type', 'employment_type', 'description'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1048 non-null   int64
 1   title            1048 non-null   object
 2   company          1046 non-null   object
 3   location         1033 non-null   object
 4   link             1048 non-null   object
 5   source           959 non-null    object
 6   date_posted      1025 non-null   object
 7   work_type        0 non-null      float64
 8   employment_type  0 non-null      float64
 9   description      1044 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 82.0+ KB

In [11]:
df.describe()

                id  work_type  employment_type
count  1048.000000        0.0              0.0
mean   1314.083969        NaN              NaN
std     772.822422        NaN              NaN
min       1.000000        NaN              NaN
25%     616.750000        NaN              NaN
50%    1303.500000        NaN              NaN
75%    2033.250000        NaN              NaN
max    2534.000000        NaN              NaN

In [12]:
df.shape

(1048, 10)

In [14]:
df.columns.tolist()

['id',
 'title',
 'company',
 'location',
 'link',
 'source',
 'date_posted',
 'work_type',
 'employment_type',
 'description']

In [16]:
df

,id,title,company,location,link,source,date_posted,work_type,employment_type,description
0,1,Data Analyst,Meta,"New York, NY",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
1,2,Data Analyst,Meta,"San Francisco, CA",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
2,3,Data Analyst,Meta,"Los Angeles, CA",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
3,4,Data Analyst,Meta,"Washington, DC",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-14,NaN,NaN,The Social Measurement team is a growing team ...
4,5,Data Analyst II,Pinterest,"Chicago, IL",https://www.linkedin.com/jobs/view/data-analys...,LinkedIn,2025-04-16,NaN,NaN,About Pinterest\n\nMillions of people around t...
...,...,...,...,...,...,...,...,...,...,...
1043,2521,Senior GIS/Data Management Analyst,"Carollo Engineers, Inc.","Arlington, VA, US",https://www.indeed.com/viewjob?jk=d21d387bd349...,indeed,2025-06-10,NaN,NaN,Overview:\n\nCarollo Engineers is an internati...
1044,2531,Data Science Senior Associate - Card Data & An...,JPMorganChase,"Wilmington, DE, US",https://www.indeed.com/viewjob?jk=80450a9ec23a...,indeed,2025-06-11,NaN,NaN,**JOB DESCRIPTION** \n\nJoin our Card Data \&...
1045,2532,Vice President Data Scientist Marketing Analyt...,JPMorganChase,"Columbus, OH, US",https://www.indeed.com/viewjob?jk=96df9a9fdbad...,indeed,2025-06-11,NaN,NaN,**JOB DESCRIPTION** \n\nWe’re driven by curio...
1046,2533,Lead Data Scientist - Finance Technology,JPMorganChase,"Jersey City, NJ, US",https://www.indeed.com/viewjob?jk=d25ce3283b43...,indeed,2025-06-11,NaN,NaN,**JOB DESCRIPTION** \n\nJoin our Finance Tech...
1047,2534,Applied AI/ML - Vice President,JPMorganChase,"New York, NY, US",https://www.indeed.com/viewjob?jk=cb932aabb3ef...,indeed,2025-06-11,NaN,NaN,**JOB DESCRIPTION** \n\nAs part of the Commer...

In [17]:
df["title"].value_counts().head(10)

title
Data Analyst                         152
Data Scientist                        75
Data Engineer                         58
Data Scientist, Product Analytics     29
Machine Learning Engineer             21
Data Engineer, Product Analytics      20
Senior Data Engineer                  13
Senior Data Analyst                   12
Junior Data Scientist                 11
**** *******                           9
Name: count, dtype: int64

In [18]:
df["company"].value_counts().head(10)

company
Meta        70
Netflix     33
Amazon      18
Google      16
****        14
Lensa        9
TikTok       8
AARATECH     8
********     8
*****        7
Name: count, dtype: int64

In [19]:
df["location"].value_counts().head(10)

location
United States                      73
New York, NY                       65
San Francisco, CA                  49
Bengaluru, Karnataka, India        40
Remote, US                         23
Seattle, WA                        15
London, England, United Kingdom    15
London Area, United Kingdom        14
Austin, TX                         13
Gurugram, Haryana, India           13
Name: count, dtype: int64